// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NashGrub.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NashGrub.Migrations
{
    [DbContext(typeof(NashGrubDbContext))]
    [Migration("20240425155440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NashGrub.Models.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hashtags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessName = "3rd and Lindsley"
                        },
                        new
                        {
                            Id = 2,
                            BusinessName = "Hattie B's Hot Chicken"
                        },
                        new
                        {
                            Id = 3,
                            BusinessName = "Loveless Cafe"
                        },
                        new
                        {
                            Id = 4,
                            BusinessName = "Pancake Pantry"
                        });
                });

            modelBuilder.Entity("NashGrub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HashtagId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HashtagId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 4, 25, 10, 54, 40, 101, DateTimeKind.Local).AddTicks(2777),
                            HashtagId = 1,
                            Message = "The service was attentive and friendly, adding to the overall wonderful dining experience."
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 4, 25, 10, 54, 40, 101, DateTimeKind.Local).AddTicks(2833),
                            HashtagId = 2,
                            Message = "he casual atmosphere makes it a great spot for a laid-back meal with family or friends. Just be prepared to leave with a satisfied belly and a newfound love for barbecue!"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 4, 25, 10, 54, 40, 101, DateTimeKind.Local).AddTicks(2835),
                            HashtagId = 3,
                            Message = "The tranquil ambiance adds to the overall dining experience, making it a great place to unwind after a long day."
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 4, 25, 10, 54, 40, 101, DateTimeKind.Local).AddTicks(2837),
                            HashtagId = 4,
                            Message = "The staff is always friendly and accommodating, adding to the welcoming atmosphere of the restaurant."
                        });
                });

            modelBuilder.Entity("NashGrub.Models.Review", b =>
                {
                    b.HasOne("NashGrub.Models.Hashtag", "Hashtag")
                        .WithMany("Reviews")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("NashGrub.Models.Hashtag", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
