// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NashGrub.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NashGrub.Migrations
{
    [DbContext(typeof(NashGrubDbContext))]
    partial class NashGrubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NashGrub.Models.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hashtags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessName = "3rdandlindsley"
                        },
                        new
                        {
                            Id = 2,
                            BusinessName = "hattieb'shotchicken"
                        },
                        new
                        {
                            Id = 3,
                            BusinessName = "lovelesscafe"
                        },
                        new
                        {
                            Id = 4,
                            BusinessName = "pancakepantry"
                        });
                });

            modelBuilder.Entity("NashGrub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HashtagId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HashtagId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 5, 8, 15, 40, 42, 99, DateTimeKind.Local).AddTicks(9240),
                            HashtagId = 1,
                            Message = "the service at #3rdandlindsley was attentive and friendly, adding to the overall wonderful dining experience."
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 5, 8, 15, 40, 42, 99, DateTimeKind.Local).AddTicks(9293),
                            HashtagId = 2,
                            Message = "the casual atmosphere at #hattieb'shotchicken makes it a great spot for a laid-back meal with family or friends. just be prepared to leave with a satisfied belly and a newfound love for barbecue!"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 5, 8, 15, 40, 42, 99, DateTimeKind.Local).AddTicks(9295),
                            HashtagId = 3,
                            Message = "the tranquil ambiance at #lovelesscafe adds to the overall dining experience, making it a great place to unwind after a long day."
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 5, 8, 15, 40, 42, 99, DateTimeKind.Local).AddTicks(9297),
                            HashtagId = 4,
                            Message = "the staff at #pancakepantry is always friendly and accommodating, adding to the welcoming atmosphere of the restaurant."
                        });
                });

            modelBuilder.Entity("NashGrub.Models.Review", b =>
                {
                    b.HasOne("NashGrub.Models.Hashtag", "Hashtag")
                        .WithMany("Reviews")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("NashGrub.Models.Hashtag", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
